### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by vladbondarenko** [dawigit/picoclock#3]
**Describe the bug**
Error message during the "make"

[ 67%] Linking CXX executable main.elf
/usr/lib/gcc/arm-none-eabi/10.3.1/../../../arm-none-eabi/bin/ld: CMakeFiles/main.dir/lib/draw.c.obj:(.bss.drawlines+0x0): multiple definition of `drawlines'; CMakeFiles/main.dir/main.c.obj:(.bss.drawlines+0x0): first defined here
/usr/lib/gcc/arm-none-eabi/10.3.1/../../../arm-none-eabi/bin/ld: lib/lcd/liblcd.a(lcd.c.obj):(.data.drawlines+0x0): multiple definition of `drawlines'; CMakeFiles/main.dir/main.c.obj:(.bss.drawlines+0x0): first defined here
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/main.dir/build.make:921: main.elf] Error 1
make[1]: *** [CMakeFiles/Makefile2:1421: CMakeFiles/main.dir/all] Error 2
make: *** [Makefile:91: all] Error 2

**To Reproduce**
GNU Make 4.3
cmake version 3.22.1
https://github.com/dawigit/picoclock on main
gcc version 11.2.0

**Expected behavior**
compilation successful

**Desktop (please complete the following information):**
 - OS: Ubuntu 22

**Comment by dawigit** [comment]
Hello Vlad,

the same problem was reported by _qw3r3wq_, but i cannot reproduce it.
Do you build on a RaspberryPi ? Or did you use 'pico_setup.sh' on your Ubuntu22?

**Comment by vladbondarenko** [comment]
Not sure what is pico_setup.sh is. Nope, im building on Ubuntu

**Comment by dawigit** [comment]
Ok! NOW i WAS able to reproduce the error. (I build on the Pi4, not Ubuntu).
So when building on Ubuntu: comment out 'uint16_t drawlines;' in 'lcd/lcd.h'.
And... linking works. I pushed the changes already.

Thank you Vlad (and Ruslanas) for reporting that issue.

**Comment by vladbondarenko** [comment]
Thanks a lot! Its working now!
