### ISSUE TITLE
picoclock install Tutorial

### ISSUE THREAD

**Issue by ha0248** [dawigit/picoclock#7]
hello dawigit,
can you write me a little tutorial for the installation of pico sdk and the picoclock? I'm trying for days to install picoclock, it does not work, I do not get anywhere. Help me, please!!!
many greetings
Dieter

**Comment by dawigit** [comment]
Hello Dieter,

If you are using Debian/Ubuntu/RaspiOS

[StartHere!](https://datasheets.raspberrypi.com/pico/getting-started-with-pico.pdf)

STEP 1:
2.1. Get the SDK and examples
The Pico Examples repository provides a set of example applications that are written using the SDK. To clone these
repositories start by creating a pico directory to keep all pico related checkouts in. These instructions create a pico
directory at /home/pi/pico.
`cd ~/`
`mkdir pico`
`cd pico`
`git clone https://github.com/raspberrypi/pico-sdk.git --branch master`
`cd pico-sdk`
`git submodule update --init`
`cd ..`
`git clone https://github.com/raspberrypi/pico-examples.git --branch master`

You also need to add a few exports to your .bashrc  (ASSUMPTION: your $HOME is /home/dieter):
`export PICO_SDK_PATH=/home/dieter/pico/pico-sdk`
`export PICO_EXAMPLES_PATH=/home/dieter/pico/pico-examples`
`export PICO_EXTRAS_PATH=/home/dieter/pico/pico-extras`
`export PICO_PLAYGROUND_PATH=/home/dieter/pico/pico-playground`
`export PICO_SDK_PATH=/home/dieter/pico/pico/pico-sdk`
`export PICO_EXAMPLES_PATH=/home/dieter/pico/pico/pico-examples`
`export PICO_EXTRAS_PATH=/home/dieter/pico/pico/pico-extras`
`export PICO_PLAYGROUND_PATH=/home/dieter/pico/pico/pico-playground`
`export PICO_EXTRAS_PATH=/home/dieter/pico/pico-extras`
`export PICO_PLAYGROUND_PATH=/home/dieter/pico/pico-playground`
`export PICO_SDK_PATH=/home/dieter/pico/pico-sdk`
`export PICO_EXAMPLES_PATH=/home/dieter/pico/pico-examples`
`export PICO_EXTRAS_PATH=/home/dieter/pico/pico-extras`
`export PICO_PLAYGROUND_PATH=/home/dieter/pico/pico-playground`

STEP 2:
2.2. Install the Toolchain
To build the applications in pico-examples, you’ll need to install some extra tools. To build projects you’ll need CMake, a
cross-platform tool used to build the software, and the GNU Embedded Toolchain for Arm. You can install both of these
via apt from the command line. Anything you already have installed will be ignored by apt.
`sudo apt update`
`sudo apt install cmake gcc-arm-none-eabi libnewlib-arm-none-eabi build-essential`

STEP 3:
Clone 'picoclock' (to your home dir: '/home/dieter/picoclock') and build it:
`cd`
`git clone https://github.com/dawigit/picoclock.git`
`cd picoclock`
`mkdir build`
`cd build`
`cmake ..`
`make`

After a successful build there'll be a 'main.uf2' file.
You can now drag'n'drop that file to your (pico) mass storage device.
That is your pico connected/reset while holding down the 'boot' button, then releasing.

Hope that helps.
IF not, then I suggest you give a few more details. WHAT does not work? Where in the process are you stuck?
What's the error? What does your terminal 'say'? Cut'n'paste that or better parts of it containing the error.

**Comment by ha0248** [comment]
Hello dawigit,
thank you very much for your quick reply. With your tutorial I got the Picclock running.
However, have at the clock a touch display, that does not work yet, I see now the s_kr.png on the display. How do I get the s_qdtm.png on the display and works with it the settings by touch?
The Picotool also does not work for me yet.
Thanks again for your effort with me
Dieter

**Comment by dawigit** [comment]
Change the settings (background, theme (flag), clockhand style&texture) by touching the gear symbol.
`alias pilo='sudo picotool load ./main.uf2 -x --bus $(picotool info | grep "device in BOOTSEL" | cut -d" " -f4 | cut -c1) --address $(picotool info | grep "device in BOOTSEL" | cut -d" " -f6)'`
So, if you're in your build directory '/home/dieter/picoclock/build' just type `pilo`

**Comment by ha0248** [comment]
Hello,
the gear icon does not work, I thought I needed the picotool to install the s_qdtm.png?
I just see you live in Germany, can we write in German?
greet Dieter
